### ISSUE TITLE
How to set zoom?

### ISSUE THREAD

**Issue by Osurac529** [trilliumeng/orion-sdk#26]
I am using the type `OrionCameraState_t` to set the `Zoom` field which appears to go from 0 to 1 not including 0.

This is the code:

```
  OrionCameraState_t camera_state;
  memset(&camera_state, 0, sizeof(camera_state));
  camera_state.Zoom = 0.5f;
  camera_state.KeepActiveCamera = 1;

  OrionPkt_t packet;
  encodeOrionCameraStatePacketStructure(&packet, &camera_state);

  if (!OrionCommSend(&packet)) {
    LOG(ERROR) << "Failed to send " << packet.ID;
    return;
  }

  bool done = false;

  while (!done) {
    OrionPkt_t packet_in;

    if (OrionCommReceive(&packet_in) &&
        ORION_PKT_CAMERA_STATE == packet_in.ID) {
      done = true;
      continue;
    }

    boost::this_thread::sleep_for(boost::chrono::microseconds(100'000));
  }
```

Whenever I look at the video output the zoom/field of view has not changed.

**Comment by treavg** [comment]
Hi @Osurac529, the note on the SDK communication document was misleading and will be corrected.  It should read _"Sending less than 1 interprets as do not change, 1 is full wide, 2 is 2X, etc."_ As you were sending a value less than 1, it is expected behavior for the zoom to remain at the current value.  Values 1 and larger should respond as you expect, where 1.0 commands full wide.
